function f = f(a,b)
%F
%    F = F(A,B)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    26-Jul-2020 16:08:26

if ((b <= a) & (0.0 < b))
    f = b;
elseif (a < b)
    f = a-(a-b).^2.*3.0;
else
    f = NaN;
end
