function out1 = f_a(y)
%F_A
%    OUT1 = F_A(Y)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    26-Jul-2020 10:59:14

if ((0.0 < y) & (y <= 2.0))
    out1 = -y;
elseif (2.0 < y)
    out1 = (y-2.0).^2.*3.0-2.0;
else
    out1 = NaN;
end
