function g = g(a,b)
%G
%    G = G(A,B)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    26-Jul-2020 21:25:37

t2 = (a < b);
t3 = (b <= a);
t4 = b.^2;
t5 = -a;
t6 = b.*2.4e+1;
t7 = (3.0./4.0 <= b);
t8 = t6+4.0;
t9 = t4.*1.2e+1;
t11 = (t3 & t7);
t12 = b+t5+1.0./6.0;
t10 = t8.^2;
t13 = t12.^2;
t14 = t10./4.8e+1;
t15 = t13.*1.2e+1;
t16 = t9+t15+3.0;
t17 = (t16 <= t14);
t18 = (t2 & t17);
t19 = (t11 | t18);
if ((t3 & t19) & (0.0 < b))
    g = 1.0./a.^5.*1.0./t4.^3.*6.842092037200928;
elseif ((t2 & t19) & (0.0 < a))
    g = 1.0./a.^4.*1.0./b.^7.*6.842092037200928;
else
    g = 0.0;
end
