#!/bin/bash
# bash ~/thindrives/Desktop/'Skill_Mismatch Result'/Fortran/Pre_Job_RED
# mv ~/Documents/* /N/slate/fanrong



# ===============================================================================================
# Calibrate: Compile

echo -e "\e[1;94m $(date) \e[0m"
cd ~/Documents
mkdir -p Skill_Mismatch
cd Skill_Mismatch
rm -r Calibration
mkdir Calibration

cp -f ~/thindrives/Desktop/Skill_Mismatch/*.f90 ~/Documents/Skill_Mismatch/Calibration
cp -f ~/thindrives/Desktop/Skill_Mismatch/Calibration/* ~/Documents/Skill_Mismatch/Calibration

module load nlopt
cd ~/Documents/Skill_Mismatch/Calibration
make -f Makefile



# ===============================================================================================
# Calibrate: Mkdir

num=1
cd ~/Documents
mkdir -p $(date +%Y%m%d)
cd $(date +%Y%m%d)
{
echo '#!/bin/bash'
echo 'export num='$num
} > number
mkdir -p Calibrate
cd Calibrate
mkdir -p $num

cp -f ~/thindrives/Desktop/'Skill_Mismatch Result'/Fortran/Run_Job_RED ~/Documents/$(date +%Y%m%d)
cp -f ~/thindrives/Desktop/'Skill_Mismatch Result'/Fortran/Calibration ~/Documents/$(date +%Y%m%d)/Calibrate/$num



# ===============================================================================================
# Calibrate: Export

rm -r ~/thindrives/Desktop/'Skill_Mismatch Result'/Fortran/Calibrate
cp -r ~/Documents/$(date +%Y%m%d)/Calibrate ~/thindrives/Desktop/'Skill_Mismatch Result'/Fortran



# ===============================================================================================
# Simulate: Compile

echo -e "\e[1;94m $(date) \e[0m"
cd ~/Documents
mkdir -p Skill_Mismatch
cd Skill_Mismatch
rm -r Simulation
mkdir Simulation

cp -f ~/thindrives/Desktop/Skill_Mismatch/*.f90 ~/Documents/Skill_Mismatch/Simulation
cp -f ~/thindrives/Desktop/Skill_Mismatch/Simulation/* ~/Documents/Skill_Mismatch/Simulation

cd ~/Documents/Skill_Mismatch/Simulation
make -f Makefile



# ===============================================================================================
# Simulate: Mkdir

cd ~/Documents
mkdir -p $(date +%Y%m%d)
cd $(date +%Y%m%d)
mkdir -p Simulate

cp -f ~/thindrives/Desktop/'Skill_Mismatch Result'/Fortran/Run_Job_RED ~/Documents/$(date +%Y%m%d)
cp -f ~/thindrives/Desktop/'Skill_Mismatch Result'/Fortran/Simulation ~/Documents/$(date +%Y%m%d)/Simulate



# ===============================================================================================
# Simulate: Export
rm -r ~/thindrives/Desktop/'Skill_Mismatch Result'/Fortran/Simulate
cp -r ~/Documents/$(date +%Y%m%d)/Simulate ~/thindrives/Desktop/'Skill_Mismatch Result'/Fortran



